version: '3'

services:
  gtpostgres:
    image: postgres:14.10
    container_name: ${STACK_NAME:-defstack}_gtpostgres
    restart: always
    environment:
      POSTGRES_DB: giteadb
      POSTGRES_USER: gitea
      POSTGRES_PASSWORD: giteapw
    ports:
     - "8432:5432"  # Map port 8432 on the host to port 5432 in the container
    volumes:
      - gtpostgres_data:/var/lib/postgresql/data
    networks:
      - mydefaultstack

  gitea:
    image: gitea/gitea:1.21.4
    container_name: ${STACK_NAME:-defstack}_gitea
    restart: always
#    depends_on:
#      - gtpostgres
    networks:
      - mydefaultstack
    # command: >
    #   /bin/sh -c "apk add --no-cache python3 py3-pip
    #   && pip3 install nbconvert"
    environment:
      - USER=${HOST_USER}
      - USER_UID=1000
      - USER_GID=1000
      - DB_TYPE=postgres
      - DB_HOST=${POSTGRES_HOSTNAME}:5432
      - DB_NAME=giteadb
      - DB_USER=gitea
      - DB_PASSWD=giteapw
      - GITEA_CUSTOM=/data/gitea/custom
    ports:
      - "8300:3000"
      - "8022:22"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gitea.tls=true"
      - "traefik.http.routers.gitea.rule=Host(`gitea.${DOMAIN_NAME}`)"
      - "traefik.http.services.gitea.loadbalancer.server.port=3000"
    volumes:
      - gitea_data:/data
      - ${PWD}/config/app.ini:/data/gitea/custom/conf/app.ini

volumes:
  gtpostgres_data:
    driver: local
  gitea_data:
    driver: local

networks:
  mydefaultstack:
    name: mydefaultstack
    external: true
